### PR TITLE
Add support for built-in kernel build

### PR DESCRIPTION
**Pull request by mjeanson**

### CODE REVIEW

**Comment by compudj** [comment]
If we want to indent de makefiles, we should settle on an indentation. Looking at the kernel makefiles, 2 spaces seems to be used a lot. In this patchset, we have a lot of single-space indentation, which is very little.

I notice many lines that contain whitespaces at the end of lines, should be removed.

I notice lines that have spaces followed by tabs, should be cleaned up.

Thanks,

Mathieu

**Comment by mjeanson** [comment]
Cleaned up indentation to be 2 spaces in all makefiles.

**Comment by mjeanson** [comment]
This patchset is ready for a second review.

**Comment by compudj** [comment]
There are still whitespaces at end of otherwise empty lines. 

Please double-check that the PR is up to date. 

----- On Dec 17, 2015, at 10:52 AM, Michael Jeanson <notifications@github.com> wrote: 

> This patchset is ready for a second review.

> —
> Reply to this email directly or view it on GitHub .

-- 
Mathieu Desnoyers 
EfficiOS Inc. 
http://www.efficios.com

**Comment by compudj** [comment]
merged, thanks!

Mathieu

**Pull request closed without merging**
